name: Deploy Satis to Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Satis configuration
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Build Satis
        # Použijeme oficiální Satis obraz přímo v shellu, to lintery neprovokuje
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/build \
            -e COMPOSER_AUTH='{"github-oauth": {"github.com": "${{ secrets.MY_SATIS_TOKEN }}"}}' \
            composer/satis /bin/sh -c "git config --global --add safe.directory /build && php /satis/bin/satis build satis.json output"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
          force_orphan: true

      - name: Delete old workflow runs
        run: |
          RUNS_TO_DELETE=$(gh run list --workflow "${{ github.workflow }}" --json databaseId --limit 100 | jq -r '.[4:].[] | .databaseId')
          
          if [ -z "$RUNS_TO_DELETE" ]; then
            echo "Žádné staré runy k smazání."
          else
            for run_id in $RUNS_TO_DELETE; do
              gh run delete "$run_id"
            done
          fi
        env:
          GH_TOKEN: ${{ github.token }}
